services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Vikas@2004"
      POSTGRES_DB: url_shortner

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always

    ports:
      - "6379:6379"

  backend:
    build:
      context: ./Backend

    container_name: backend
    restart: always

    depends_on:
      - postgres
      - redis

    env_file:
      - ./Backend/.env.docker

    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "http://localhost:3000/api/v1"
        NEXT_PUBLIC_BASE_URL: "http://localhost:3000"

    container_name: frontend
    restart: always

    depends_on:
      - backend

    ports:
      - "3001:3001"

volumes:
  postgres_data: